name: interview
description: "Mücahit Şimşek - Interview Project"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
 
  #core
  equatable: ^2.0.5

  #modules
  gen: 
    path: module/gen
  common:
    path: module/common

  #firebase_modules
  firebase_core: ^2.31.0
  firebase_remote_config: ^4.4.5
  firebase_analytics: ^10.10.5

  #navigation
  auto_route: ^8.1.3

  #network
  vexana: ^3.5.4

  #state
  flutter_bloc: ^8.1.5
  bloc: ^8.1.4

  #config
  get_it: ^7.7.0

  #utils
  logger: ^2.2.0
  flutter_native_splash: ^2.4.0
  kartal: ^4.0.3

dev_dependencies:
  auto_route_generator: ^8.0.0
  build_runner: ^2.4.9

  flutter_test:
    sdk: flutter
  
  very_good_analysis: ^5.1.0



flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

